<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-windows10.0.19041.0;</TargetFrameworks>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<UseWinUI>true</UseWinUI>
		<DefineConstants>$(DefineConstants);WINUI</DefineConstants>
		<EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
		<GenerateLibraryLayout>true</GenerateLibraryLayout>
		<RootNamespace>DSoft.WizardControl</RootNamespace>
		<AssemblyName>DSoft.WizardControl.WinUI</AssemblyName>
		<Product>$(AssemblyName) ($(TargetFramework))</Product>
		<Description>DSoft.WizardControl.WinUI is a simple wizard custom control for WinUI 3.x</Description>
		<PackageTags>WinUI Wizard</PackageTags>
		<PackageReleaseNotes>Added .NET 10 support and removed support for .NET 6, 8 and 9
		</PackageReleaseNotes>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1721" />
		<ProjectReference Include="..\DSoft.WizardControl.Core\DSoft.WizardControl.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>
